[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Alex Macrae <alex@mungorae.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
